name: covfiguresapp
description: An app that provides important current data&#x2F;information about COVID-19 relative to the user’s location.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flappy_search_bar: ^1.7.2
  http: ^0.12.1
  flutter_spinkit: ^4.1.2+1
  geolocator: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true

